// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    aCheck: function(message, test, timeout) {
      var isDone;
      if (timeout == null) {
        timeout = 20;
      }
      isDone = false;
      runs(function() {
        return test(function() {
          return isDone = true;
        });
      });
      return waitsFor((function() {
        return isDone;
      }), message, timeout);
    },
    aFail: function(it, done) {
      var _this = this;
      return function(msg) {
        it.fail(msg);
        return done();
      };
    }
  };

}).call(this);
